//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        public string MaGiaoVien { get; set; }
        public string TenGiaoVien { get; set; }
        public string HocVi { get; set; }
        public string SoDienThoai { get; set; }
        public string MaKhoa { get; set; }
    }
}
