//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public string MaSinhVien { get; set; }
        public string MaKhoaHoc { get; set; }
        public int LanThi { get; set; }
        public double Diem { get; set; }
    }
}
