//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TieuLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public string MaSinhVien { get; set; }
        public string HoSinhVien { get; set; }
        public string TenSinhVien { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string Phai { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string MaKhoa { get; set; }
    }
}
