//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TL_LT_Web_14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoKhau
    {
        public string SoSoHoKhau { get; set; }
        public string DiaChi { get; set; }
        public string MaPhuong { get; set; }
    }
}
