//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TL_LT_Web_14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanKhau
    {
        public string MaNhanKhau { get; set; }
        public string TenNhanKhau { get; set; }
        public string PhaiNu { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SoCMND { get; set; }
        public string MaTrinhDoVanHoa { get; set; }
        public string MaNgoaiNgu { get; set; }
        public string SoSoHoKhau { get; set; }
        public string GhiChu { get; set; }
    }
}
