//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TL_LT_Web_14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrinhDo
    {
        public string MaTrinhDoVanHoa { get; set; }
        public string TenTrinhDoVanHoa { get; set; }
    }
}
